### ISSUE TITLE
단일 웹 서버 배포 중 8080 포트로 요청이 거부되는 현상

### ISSUE THREAD

**Issue by zxcv9203** [reliability-engineering-hub/terraform-up-and-running#3]
단일 웹서버 배포중에 다음과 같은 에러가 계속 발생합니다..

혹시 원인이나 해결책을 아시나요 😢 

```
curl: (7) Failed to connect to x.x.x.x port 8080 after 148 ms: Couldn't connect to server
```

**Comment by lcw729** [comment]
AWS 네트워크 설정 문제로 추측되는데 1~3을 확인해주시고, 내일 같이 원인을 찾아보는 것이 좋아보입니다. 😊
1. subnet의 nacl 인바운드와 아웃바운드 설정을 확인한다. ( public subnet 인가요? )
2. ec2에 public ip가 자동 할당되었는지 확인한다.
3. ec2에 대한 security group의 인바운드와 아웃바운드 설정을 확인한다.

**Comment by zxcv9203** [comment]
Ubuntu Version 문제였던 것으로 판단됩니다. 22.04 -> 20.04로 낮출 경우 정상 작동
